; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

monitor_speed = 115200
upload_speed = 115200
build_flags =
    -D SDFAT_FILE_TYPE=2
    -D ENABLE_ARDUINO_FEATURES=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

build_type = debug
monitor_filters = esp32_exception_decoder 
lib_deps =
    olikraus/U8g2
    https://github.com/Eclypsee/SparkFun_Qwiic_XM125_Arduino_Library.git
    https://github.com/swissbyte/AccelStepper.git